### ISSUE TITLE
minor feature request for github: want a short description of redis functions

### ISSUE THREAD

**Issue by drose28357** [hobbyquaker/ccu-addon-redis#1]
Please add a link to a wiki or a short discription on what redis is yoused for in the readme.

for example this one https://en.wikipedia.org/wiki/Redis or https://de.wikipedia.org/wiki/Redis

**Comment by hobbyquaker** [comment]
Hmm, seh ich keine Notwendigkeit. Die Redis Homepage ist ja schon verlinkt und ein wenig Google bedienen kann auch jeder ;-) Ich sehe das bei diesem Projekt genauso wie auch bei https://github.com/hobbyquaker/ccu-addon-mosquitto ...
_wer nicht weiss was es ist der braucht es auch nicht._ ;-)

**Comment by drose28357** [comment]
Ist für mich o.k..
Nun, ich bin eher von der Marketing-Fraktion, d.h. nur wer sein Produkt erklärt und bewirbt, wird User finden.
